SELECT
CITY,
MIN(TOTALPRICE) AS MINPRICE,
MAX(TOTALPRICE) AS MAXPRICE,
COUNT(FICHENO) ROWCOUNT_,
SUM(TOTALPRICE) TOTALPRICE,
AVG(TOTALPRICE) AVGPRICE
FROM SALES

 GROUP BY CITY
 ORDER BY SUM(TOTALPRICE)