SELECT
U.NAMESURNAME,COUNT(A.ID) AS ADRESSAYISI,COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI,
COUNT(DISTINCT CT.ID) SEHIRSAYISI
FROM
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID

GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>2