-- ÜRÜNLERÝN FÝYAT ANALÝZÝ

SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET
FROM

ITEMS ITM
ORDER BY ITM.ITEMNAME